name: uncompyle6 (osx)

on:
  push:
    branches: [ python-3.3-to-3.5 ]
  pull_request:
    branches: [ python-3.3-to-3.5 ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macOS]
        python-version: [3.3, 3.4, 3.5]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Until the next xdis release
        pip install git+git://github.com/rocky/python-xdis.git#egg=xdis
        pip install -e .
        pip install -r requirements-dev.txt
    - name: Test uncompyle6
      run: |
        make check
